AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Publish Data S3 Function

Parameters:
  QueueMetadata:
    Type: String
    Description: Enter the name of the Metadata Queue.
  StageBucket:
    Type: String
    Default: mytiki-publish
    Description: Enter the name of the staging bucket.
  StageCompression:
    Type: String
    Description: Enter the staging file compression (gzip, none).
  StageFileType:
    Type: String
    Default: csv
    Description: Enter the source file type (csv).
  StageWildcard:
    Type: String
    Description: Enter the wildcard syntax to filter events.
  DestBucket:
    Type: String
    Description: Enter the name of the output file bucket.
  DestTable:
    Type: String
    Description: Enter the table name for the dataset.

Resources:
  Function:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
    Properties:
      CodeUri: ../..
      Handler: bootstrap
      Runtime: provided.al2
      MemorySize: 1024
      Timeout: 900
      Architectures:
        - x86_64
      Events:
        EventBridgeRule:
          Type: EventBridgeRule
          Properties:
            Pattern: !Sub "{\"source\":[\"aws.s3\"],\"detail-type\":[\"Object Created\"],\"detail\":{\"bucket\":{\"name\":[\"mytiki-publish\"]},\"object\":{\"key\":[{\"wildcard\":\"${StageWildcard}\"}]}}}"
            RuleName: !Ref DestTable
            State: ENABLED
      Environment:
        Variables:
          TIKI_REGION: !Ref AWS::Region
          TIKI_BUCKET: !Ref DestBucket
          TIKI_TABLE: !Ref DestTable
          TIKI_FILE_TYPE: !Ref StageFileType
          TIKI_COMPRESSION: !Ref StageCompression
          TIKI_QUEUE: !Sub https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/${QueueMetadata}
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref StageBucket
        - SQSSendMessagePolicy:
            QueueName: !Ref QueueMetadata
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:ListBucket
                - s3:GetBucketLocation
                - s3:GetObjectVersion
                - s3:GetObjectAttributes
                - s3:PutObject
              Resource:
                - !Sub "arn:aws:s3:::${DestBucket}"
                - !Sub "arn:aws:s3:::${DestBucket}/*"
