AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Ingest - S3 Lambda

Parameters:
  QueueArn:
    Description: Arn for the SQSEvent Queue
    Type: String
  SourceBucket:
    Type: String
    Description: Enter the source bucket.
  DestinationBucket:
    Type: String
    Description: Enter the destination bucket.
  TableName:
    Type: String
    Description: Enter the destination table name.
  FileType:
    Type: String
    Description: Enter the source file type (csv).
  Compression:
    Type: String
    Default: none
    Description: Enter the source file compression (gzip, none).
  MetadataQueue:
    Type: String
    Default: none
    Description: Enter the name of the Metadata Queue.

Resources:
  Function:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
    Properties:
      CodeUri: ..
      Handler: bootstrap
      Runtime: provided.al2
      MemorySize: 512
      Timeout: 20
      Architectures:
        - arm64
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Enabled: true
            FunctionResponseTypes:
              - ReportBatchItemFailures
            BatchSize: 10
            Queue: !Ref QueueArn
      Environment:
        Variables:
          TIKI_REGION: !Ref AWS::Region
          TIKI_BUCKET: !Ref DestinationBucket
          TIKI_TABLE: !Ref TableName
          TIKI_FILE_TYPE: !Ref FileType
          TIKI_COMPRESSION: !Ref Compression
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref SourceBucket
        - S3CrudPolicy:
            BucketName: !Ref DestinationBucket
        - SQSSendMessagePolicy:
            QueueName: !Ref MetadataQueue
