AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Ingest - S3 SLambda

Parameters:
  QueueArn:
    Description: Arn for the SQSEvent Queue
    Type: String
  KeyPrefix:
    Type: String
    Description: The name of the key prefix to process events for.
  BucketName:
    Type: String
    Description: Enter the destination bucket.
  TableName:
    Type: String
    Description: Enter the destination table name.
  FileType:
    Type: String
    Description: Enter the source file type (csv).
  Compression:
    Type: String
    Default: none
    Description: Enter the source file compression (gzip, none).

Resources:
  Function:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
    Properties:
      CodeUri: ..
      Handler: bootstrap
      Runtime: provided.al2
    MemorySize: 512
    Timeout: 20
    Architectures:
      - arm64
    Events:
      SQSEvent:
        Type: SQS
        Properties:
          Enabled: true
          FunctionResponseTypes:
            - ReportBatchItemFailures
          BatchSize: 10
          Queue: !Ref QueueArn
          FilterCriteria:
            Filters:
              - Pattern: !Sub "{ \"body\" : { \"s3\" : { \"key\" : [ { \"prefix\": \"${KeyPrefix}/\" } ] } } }"
    Environment:
      Variables:
        TIKI_REGION: !Ref AWS::Region
        TIKI_BUCKET: !Ref BucketName
        TIKI_TABLE: !Ref TableName
        TIKI_FILE_TYPE: !Ref FileType
        TIKI_COMPRESSION: !Ref Compression

