name: Report
on:
  workflow_run:
    workflows: ['Tests']
    types:
      - completed
jobs:
  json:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: JSON Tests
          path: '*.json'
          reporter: mocha-json
